# Example Gitaly configuration file

socket_path = "{{GITALY_SOCKET_PATH}}"

# # Optional: listen on a TCP socket. This is insecure (no authentication)
# listen_addr = "localhost:9999"
#

[[storage]]
name = "default"
path = "{{GITLAB_REPOS_DIR}}"

[gitaly-ruby]
# The directory where gitaly-ruby is installed
dir = "/home/git/gitaly/ruby"

[gitlab-shell]
# The directory where gitlab-shell is installed
dir = "/home/git/gitlab-shell"
